name: Deploy to Hostinger

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Hostinger
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 65002 154.49.245.118 >> ~/.ssh/known_hosts
          scp -P 65002 -r dist/ u587430202@154.49.245.118:public_html/

