- name: Deploy to Hostinger
  run: |
    set -x  # This will print each command before it's executed
    mkdir -p ~/.ssh
    echo "${{ secrets.HOSTINGER_DEPLOY_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H dfernandezfoe.com >> ~/.ssh/known_hosts
    scp -r dist/ dfernandezcode@gmail.com@dfernandezfoe.com:public_html/
  env:
    HOSTINGER_DEPLOY_KEY: ${{ secrets.HOSTINGER_DEPLOY_KEY }}
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Hostinger
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H dfernandezfoe.com >> ~/.ssh/known_hosts
          scp -r dist/ dfernandezcode@gmail.com@dfernandezfoe.com:public_html/
        env:
          HOSTINGER_DEPLOY_KEY: ${{ secrets.HOSTINGER_DEPLOY_KEY }}
