name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - default
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Deploy to Hostinger
      run: |
        # Add your Hostinger deployment script or commands here
        # This could be FTP/SFTP commands or API calls to Hostinger
